weight: "bert-base-multilingual-cased"
max_length: 32
batch_size: 32
learning_rate: 0.0005
seq2seq_hp:
  lr: 0.0005
  max_length: 32
  n_samples: 5
  batch_size: 32
  input_size: 150000
  word_vec_size: 256
  hidden_size: 256
  output_size: 150000